#!/bin/bash
function prepare_commit_message() {
  local prefix_message
  local commit_message
  prefix_message=$(dp_scm_compliant.sh)
  [[ $? != 0 ]] && exit 1
  commit_message=$(cat $1)
  source "$(dirname $0)/validators/gitlint.sh"
  validate "${commit_message}" || exit $?
  printf "$prefix_message ${commit_message}"> $1
}
prepare_commit_message "$1"
