#!/bin/bash
function prepare_commit_message() {
  local prefix_message
  local commit_message
  prefix_message=$(dp_scm_compliant.sh) || exit $?
  commit_message=$(cat "$1")
  #shellcheck source=plugin/app/plugins/pipeline_plugin/tools/scm/git/templates/hooks/validators/gitlint.sh
  source "$(dirname "$0")/validators/gitlint.sh"
  validate "${commit_message}" || exit $?
  dp_log.sh '[INFO]  [OK] [gitlint]'
  printf "%s %s" "$prefix_message" "${commit_message}" >"$1"
}
prepare_commit_message "$1"
